// Use only with a disposable test database/schema. No third-party browser package needed.
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const origin=process.env.APP_URL;
if(!origin || !process.env.E2E_DISPOSABLE_DATABASE) throw new Error('Set APP_URL and E2E_DISPOSABLE_DATABASE=1 for an isolated test server');
const tabs=await(await fetch((process.env.BROWSER_DEBUG_URL||'http://localhost:9223')+'/json/list')).json();
const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);
await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let next=1;const pending=new Map();const errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text)};
function send(method,params={}){return new Promise((resolve,reject)=>{const id=next++;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))})}
async function js(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
async function wait(expression){const end=Date.now()+15000;while(Date.now()<end){if(await js(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timeout: '+expression+'\n'+await js('document.body.innerText'))}
async function button(text){await js(`(()=>{const e=[...document.querySelectorAll('button,a')].find(e=>e.textContent.trim()===${JSON.stringify(text)});if(!e)throw Error('Missing '+${JSON.stringify(text)});e.click()})()`)}
async function fill(selector,value){await js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing input');const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:e.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(p,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}))})()`)}
async function label(name,value){const selector=await js(`(()=>{const l=[...document.querySelectorAll('label')].find(e=>e.childNodes[0]?.textContent.trim()===${JSON.stringify(name)});if(!l)throw Error('Missing label '+${JSON.stringify(name)});const e=l.querySelector('input,select,textarea');e.dataset.smoke='target';return '[data-smoke="target"]'})()`);await fill(selector,value);await js(`document.querySelector('[data-smoke="target"]').removeAttribute('data-smoke')`)}
async function nextQuestion(title){await button('Продолжить →');await wait(`document.querySelector('.active-question h2')?.textContent===${JSON.stringify(title)}`)}
async function screenshot(name){await mkdir('var/screenshots',{recursive:true});const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile('var/screenshots/'+name+'.png',Buffer.from(r.data,'base64'))}
try{
 await send('Runtime.enable');await send('Page.enable');await send('Network.clearBrowserCookies');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await send('Page.navigate',{url:origin+'/register'});await wait(`document.querySelector('.active-question h2')?.textContent==='Как вас зовут?'`);
 await fill('input','Сергей');await nextQuestion('Укажите вашу фамилию');await fill('input','Данилюк');await nextQuestion('Укажите номер телефона');await fill('input','+79991234567');await nextQuestion('Укажите e-mail');
 await fill('input','browser-'+Date.now()+'@example.test');await nextQuestion('Придумайте пароль');await fill('input','Browser-E2E-password-0987');await nextQuestion('Я принимаю условия использования сервиса и согласен с обработкой персональных данных.');await js(`document.querySelector('input[type=checkbox]').click()`);await nextQuestion('Проверьте ваши данные');await button('Создать аккаунт');await wait(`document.body.innerText.includes('Аккаунт создан')`);await button('Создать Point');
 await wait(`document.querySelector('.active-question h2')?.textContent==='На кого будет оформлен Point?'`);await screenshot('point-desktop');await button('ООО');await nextQuestion('Введите ИНН организации или ИП');await label('ИНН','7707083893');await button('Заполнить вручную');await label('Название / ФИО ИП','ООО Браузерный тест');await label('Полное название','ООО Браузерный тест');await label('КПП','773601001');await label('ОГРН','1027700132195');await label('Юридический адрес','Москва');await label('ФИО руководителя / ИП','Тестовый Руководитель');await button('Да, всё верно');await nextQuestion('Теперь создадим ваш Point. Укажите адрес точки.');
 await label('Адрес','Москва, Ленинградский проспект, 36');await button('Указать адрес и координаты вручную');await label('Полный адрес','Москва, Ленинградский проспект, 36');await label('Город','Москва');await label('Улица','Ленинградский проспект');await label('Дом','36');await label('Широта адреса','55.790');await label('Долгота адреса','37.560');await label('Широта входа','55.791');await label('Долгота входа','37.561');await button('Показать расположение');await button('Всё верно');await nextQuestion('Где находится вход в Point?');await button('С улицы');await nextQuestion('Подскажите, как курьеру найти вход');await fill('textarea','Справа от аптеки');await nextQuestion('Какой это тип помещения?');await button('ПВЗ');await nextQuestion('Какие операции доступны в вашей точке?');await button('Выдача заказов');await button('Приём отправлений');await nextQuestion('Сколько посылок примерно может одновременно находиться у вас?');await button('до 100');await nextQuestion('Какой максимальный вес одного отправления вы готовы принимать?');await button('до 20 кг');await nextQuestion('Когда работает ваша точка?');await screenshot('point-schedule');await nextQuestion('Покажите, как выглядит ваш Point');
 // This image is an ephemeral test fixture, stored only in the disposable schema.
 const png=await send('Page.captureScreenshot',{format:'png'});await writeFile('var/e2e-fixture.png',Buffer.from(png.data,'base64'));
 async function upload(){const doc=await send('DOM.getDocument');const node=await send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'input[type=file]'});await send('DOM.setFileInputFiles',{nodeId:node.nodeId,files:[resolve('var/e2e-fixture.png')]})}
 await upload();await wait(`document.querySelectorAll('.active-question .upload-item').length===1`);await label('Категория','interior');await upload();await wait(`document.querySelectorAll('.active-question .upload-item').length===2`);await nextQuestion('Кто будет основным контактным лицом этой точки?');await button('Другой человек');await nextQuestion('Как зовут контактное лицо?');await fill('.active-question input','Иван');await nextQuestion('Телефон контактного лица');await fill('.active-question input','+79990000000');await nextQuestion('E-mail контактного лица');await fill('.active-question input','ivan@example.test');await nextQuestion('Готово. Проверьте информацию о вашем Point.');
 await js(`document.querySelector('button[aria-label="Изменить: Кто будет основным контактным лицом этой точки?"]').click()`);await wait(`document.querySelector('.active-question h2')?.textContent==='Кто будет основным контактным лицом этой точки?'`);await button('Я');await nextQuestion('Готово. Проверьте информацию о вашем Point.');
 if(await js(`document.querySelector('.summary-list').textContent.includes('ivan@example.test')`))throw Error('Stale contact leaked into review');
 await screenshot('point-review');await button('Отправить на проверку');await wait(`document.body.innerText.includes('Point отправлен на проверку')`);await button('Перейти к моим Point');await wait(`document.body.innerText.includes('На проверке')`);await screenshot('my-points');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('Full browser E2E passed: register → Point → manual organization/address → independent coordinates → schedule → photo uploads → conditional contact edit → review → submit → My Points.');
}finally{ws.close()}
