// Continues scripts/browser-e2e.mjs in its disposable schema; promote that test user first.
import {writeFile} from 'node:fs/promises';
const origin=process.env.APP_URL;if(!origin||!process.env.E2E_DISPOSABLE_DATABASE)throw Error('Disposable test server required');
const tabs=await(await fetch('http://localhost:9223/json/list')).json();const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});let n=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}};
function send(method,params={}){return new Promise((resolve,reject)=>{const id=++n;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))})}
async function js(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
async function wait(e){const end=Date.now()+12000;while(Date.now()<end){if(await js(e))return;await new Promise(r=>setTimeout(r,100))}throw Error('Timeout '+e+'\n'+await js('document.body.innerText'))}
async function button(text){await js(`(()=>{const e=[...document.querySelectorAll('button,a,summary')].find(e=>e.textContent.trim()===${JSON.stringify(text)});if(!e)throw Error('Missing button '+${JSON.stringify(text)});e.click()})()`)}
async function label(name,value){await js(`(()=>{const l=[...document.querySelectorAll('label')].find(e=>e.childNodes[0]?.textContent.trim()===${JSON.stringify(name)});if(!l)throw Error('Missing label');const e=l.querySelector('input,select,textarea');const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:e.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(p,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event(e.tagName==='SELECT'?'change':'input',{bubbles:true}))})()`)}
try{
 await send('Page.navigate',{url:origin+'/admin/scenarios'});await wait(`document.body.innerText.includes('POINT_REGISTRATION')`);await button('Регистрация Point');await wait(`document.body.innerText.includes('Создать / открыть черновик')`);await button('Создать / открыть черновик');await wait(`document.body.innerText.includes('Добавить вопрос')`);await button('+ Добавить вопрос');await label('Текст вопроса','Есть ли парковка рядом с вашей точкой?');await label('Тип','YES_NO');await button('Дополнительные настройки');await label('Question key','parking');await button('Сохранить');await wait(`!document.body.innerText.includes('есть несохранённые изменения')`);
 const shot=await send('Page.captureScreenshot',{format:'png'});await writeFile('var/screenshots/admin-editor.png',Buffer.from(shot.data,'base64'));
 await button('Опубликовать');await wait(`document.querySelector('[aria-label="Публикация сценария"]')!==null`);await js(`document.querySelector('[aria-label="Публикация сценария"] button.primary').click()`);await wait(`document.body.innerText.includes('Создать / открыть черновик')`);
 await send('Page.navigate',{url:origin+'/points/new'});await wait(`document.querySelector('.active-question h2')?.textContent==='На кого будет оформлен Point?'`);await button('ООО');await button('Продолжить →');await wait(`document.querySelector('.active-question h2')?.textContent==='Введите ИНН организации или ИП'`);await label('Использовать организацию','0');await button('Да, всё верно');await button('Продолжить →');await wait(`document.querySelector('.active-question h2')?.textContent==='Есть ли парковка рядом с вашей точкой?'`);await button('Да');await button('Продолжить →');await wait(`document.querySelector('.active-question h2')?.textContent==='Теперь создадим ваш Point. Укажите адрес точки.'`);
 const result=await js(`(async()=>{const res=await fetch('/api/registration/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:'POINT_REGISTRATION'})});const {session}=await res.json();return {version:session.version,parking:session.answers.parking}})()`);if(result.version!==2||result.parking!==true)throw Error('Dynamic custom answer not saved');
 await send('Page.navigate',{url:origin+'/admin/applications'});await wait(`document.querySelector('tbody a')!==null`);await js(`document.querySelector('tbody a').click()`);await wait(`document.body.innerText.includes('Решение по заявке')`);await label('Комментарий','Добавьте уточнение для курьера');await button('Запросить изменения');await wait(`!document.body.innerText.includes('Решение по заявке')&&document.body.innerText.includes('Исправьте заявку')`);
 console.log('Admin browser E2E passed: create draft → custom YES_NO → publish v2 → dynamic runtime answer → application moderation.');
}finally{ws.close()}
