CREATE TABLE users (
 id text PRIMARY KEY, first_name text NOT NULL, last_name text NOT NULL, phone text NOT NULL,
 email text NOT NULL, password_hash text NOT NULL, role text NOT NULL DEFAULT 'partner' CHECK(role IN ('partner','admin')),
 consent_at timestamptz NOT NULL DEFAULT now(), email_verified_at timestamptz, phone_verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email ON users(lower(email));
CREATE TABLE auth_sessions(token_hash text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL);
CREATE TABLE organizations(id text PRIMARY KEY, owner_id text NOT NULL REFERENCES users(id), type text NOT NULL, inn text NOT NULL, kpp text NOT NULL DEFAULT '', ogrn text NOT NULL DEFAULT '', ogrnip text NOT NULL DEFAULT '', short_name text NOT NULL, full_name text NOT NULL DEFAULT '', legal_address text NOT NULL DEFAULT '', director_name text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(owner_id,inn));
CREATE INDEX organizations_owner ON organizations(owner_id);
CREATE TABLE questionnaire_scenarios(id text PRIMARY KEY, code text UNIQUE NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', current_version_id text, created_at timestamptz NOT NULL DEFAULT now());
-- Version graph is one typed, validated document: questions/options/conditions are immutable together.
CREATE TABLE questionnaire_versions(id text PRIMARY KEY, scenario_id text NOT NULL REFERENCES questionnaire_scenarios(id), number integer NOT NULL, status text NOT NULL CHECK(status IN ('DRAFT','PUBLISHED','ARCHIVED')), graph jsonb NOT NULL, created_by text REFERENCES users(id), published_by text REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz, revision integer NOT NULL DEFAULT 1, UNIQUE(scenario_id,number));
CREATE UNIQUE INDEX one_draft ON questionnaire_versions(scenario_id) WHERE status='DRAFT';
ALTER TABLE questionnaire_scenarios ADD CONSTRAINT current_version_fk FOREIGN KEY(current_version_id) REFERENCES questionnaire_versions(id);
CREATE FUNCTION protect_published_version() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF OLD.status <> 'DRAFT' AND (TG_OP='DELETE' OR NEW.graph IS DISTINCT FROM OLD.graph OR NEW.number <> OLD.number OR NEW.scenario_id <> OLD.scenario_id OR NEW.status='DRAFT') THEN RAISE EXCEPTION 'Published version is immutable'; END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
CREATE TRIGGER immutable_version BEFORE UPDATE OR DELETE ON questionnaire_versions FOR EACH ROW EXECUTE FUNCTION protect_published_version();
CREATE TABLE questionnaire_sessions(id text PRIMARY KEY, user_id text REFERENCES users(id), owner_token_hash text NOT NULL, scenario_version_id text NOT NULL REFERENCES questionnaire_versions(id), status text NOT NULL DEFAULT 'IN_PROGRESS' CHECK(status IN ('IN_PROGRESS','COMPLETED','CANCELLED')), credential_hash text, entity_id text, started_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE INDEX sessions_user ON questionnaire_sessions(user_id,status);
CREATE INDEX sessions_owner ON questionnaire_sessions(owner_token_hash,status);
CREATE TABLE questionnaire_answers(session_id text NOT NULL REFERENCES questionnaire_sessions(id), question_key text NOT NULL, value_json jsonb NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(session_id,question_key));
CREATE TABLE points(id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), owner_id text NOT NULL REFERENCES users(id), name text NOT NULL, formatted_address text NOT NULL, country text NOT NULL DEFAULT '', region text NOT NULL DEFAULT '', city text NOT NULL DEFAULT '', street text NOT NULL DEFAULT '', house text NOT NULL DEFAULT '', building text NOT NULL DEFAULT '', postal_code text NOT NULL DEFAULT '', address_latitude numeric(10,7) NOT NULL CHECK(address_latitude BETWEEN -90 AND 90), address_longitude numeric(10,7) NOT NULL CHECK(address_longitude BETWEEN -180 AND 180), entrance_latitude numeric(10,7) NOT NULL CHECK(entrance_latitude BETWEEN -90 AND 90), entrance_longitude numeric(10,7) NOT NULL CHECK(entrance_longitude BETWEEN -180 AND 180), entrance_type text NOT NULL, courier_comment text NOT NULL DEFAULT '', premise_type text NOT NULL, operations jsonb NOT NULL, storage_capacity text NOT NULL, max_parcel_weight text NOT NULL, schedule jsonb NOT NULL, contact_is_owner boolean NOT NULL, contact_name text NOT NULL, contact_phone text NOT NULL, contact_email text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','ACTIVE','SUSPENDED','CLOSED')), created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX points_organization ON points(organization_id);
CREATE INDEX points_owner ON points(owner_id);
CREATE TABLE point_applications(id text PRIMARY KEY, point_id text NOT NULL UNIQUE REFERENCES points(id), session_id text NOT NULL UNIQUE REFERENCES questionnaire_sessions(id), status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','IN_REVIEW','NEEDS_CHANGES','APPROVED','REJECTED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX applications_status_created ON point_applications(status,created_at DESC);
CREATE TABLE audit_events(id text PRIMARY KEY, actor_id text REFERENCES users(id), application_id text REFERENCES point_applications(id), version_id text REFERENCES questionnaire_versions(id), action text NOT NULL, comment text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE attachments(id text PRIMARY KEY, session_id text NOT NULL REFERENCES questionnaire_sessions(id), question_key text NOT NULL, point_id text REFERENCES points(id), storage_name text UNIQUE NOT NULL, mime text NOT NULL, size bigint NOT NULL, original_name text NOT NULL, category text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX attachments_session ON attachments(session_id);
CREATE TABLE verification_challenges(id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), channel text NOT NULL, target text NOT NULL, code_hash text NOT NULL, attempts int NOT NULL DEFAULT 0, expires_at timestamptz NOT NULL, used_at timestamptz);
